
[tool.yapf]
based_on_style = "yapf"
coalesce_brackets = true
continuation_indent_width = 2
indent_dictionary_value = false
split_before_named_assigns = false
split_before_closing_bracket = false
split_before_logical_operator = true
allow_split_before_dict_value = false
blank_line_before_nested_class_or_def = false


[tool.isort]
skip_gitignore = true